### ISSUE TITLE
Under virtualenv install

### ISSUE THREAD

**Issue by webstory** [Zubax/zubax_documentation_portal#5]
I have installed using following scripts:

git clone https://github.com/Zubax/zubax_documentation_portal.git
cd zubax_documentation_portal/
sudo aptitude install python3-pip node-less python3-dev
sudo pip3 install virtualenv
virtualenv-3.4 .venv
source .venv/bin/activate
pip3 install -r requirements.txt
pip3 install html5lib                # missing dependency.
export SESSION_SECRET='1234'
./run.py

You know what I mean.
Thanks.

**Comment by pavel-kirienko** [comment]
Thanks! Fixed in master.
